# Generated by Django 3.2.9 on 2022-08-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lasttname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
            ],
        ),
    ]
